In [2]:
import torch

In [10]:
torch.__version__

'2.0.1'

In [6]:
print(torch.backends.mps.is_available())


True


In [8]:
pip install torch==2.4.0

  Obtaining dependency information for torch==2.4.0 from https://files.pythonhosted.org/packages/b7/d0/5e8f96d83889e77b478b90e7d8d24a5fc14c5c9350c6b93d071f45f39096/torch-2.4.0-cp311-none-macosx_11_0_arm64.whl.metadata
  Obtaining dependency information for typing-extensions>=4.8.0 from https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 MB 27.7 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1
    Uninstalling torch-2.0.1:
      Successfully uninstalled torch-2.0.1
Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch

In [6]:
torch.__version__

'2.4.0'

In [8]:
print(torch.backends.mps.is_available())


True


In [16]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1,2,3])
tensor2d = torch.tensor([[1,2],[3,4]])
tensor3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [18]:
print(tensor2d)

tensor([[1, 2],
        [3, 4]])


In [20]:
print(tensor2d.shape)

torch.Size([2, 2])


In [24]:
tensor2d1 = torch.tensor([[1,2,3],[4,5,6]])
print(tensor2d1.shape)

torch.Size([2, 3])


In [26]:
print(tensor2d1.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [28]:
print(tensor2d1.shape)

torch.Size([2, 3])


In [32]:
print(tensor2d1.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [34]:
print(tensor2d1.matmul(tensor2d1.T))

tensor([[14, 32],
        [32, 77]])


In [36]:
#https://pytorch.org/docs/stable/tensors.html
print(tensor2d1@tensor2d1.T)

tensor([[14, 32],
        [32, 77]])


In [48]:
#logistic regression forward pass which can be seen in single layer neural network
import torch.nn.functional as F
from torch.autograd import grad
y = torch.tensor([1.0]) #true label
x1 = torch.tensor([1.1]) #input feature
w1 = torch.tensor([2.2],requires_grad = True) #weight parameter
b = torch.tensor([0.0],requires_grad = True)#bias unit
z = x1 * w1 + b #net input
a = torch.sigmoid(z) #Activation
loss = F.binary_cross_entropy(a,y)
#back propagation dL/dw1 = du/dw1*dz/du*da/dz*dL/da where x1*w1 = u
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [44]:
print(loss)

tensor(0.0852)
